### ISSUE TITLE
Bug:Yale Home migration breaks lock access

### ISSUE THREAD

**Issue by hanstor** [homebridge-plugins/homebridge-august#61] opened 2023-05-26 11:32 UTC
### Describe The Bug

Yale has migrated all non-us-users to a new platform. This breaks access to all locks

### To Reproduce

Log in to non-us account

### Expected behavior

Locks should appear

### Relevant log output

```shell
[August] Discover Devices: TypeError: Cannot convert undefined or null to object
```

### Config for homebridge-august

```shell
{
            "name": "August",
            "credentials": {
                "augustId": "x@gmail.com",
                "password": "xxxxx",
                "installId": "xxxxx
                "notice": "Keep your tokens a secret!",
                "isValidated": true
            },
            "platform": "August"
        }
```

### Device & Model

Yale Linus, Yale L3

### Node.js Version

v18.16.0

### NPM Version

v9.6.5

### Homebridge Version

v1.6.1

### Homebridge August Plugin Version

v1.1.0

### Homebridge Config UI X Plugin Version

v4.50.4

### Operating System

macOS

**Comment by donavanbecker** [comment] 2023-05-26 12:00
duplicate of #60

**Closed as completed** 2023-05-26 12:00 UTC
Labels: bug
