### ISSUE TITLE
Bug: Discover Devices 2: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by adyrobady** [homebridge-plugins/homebridge-august#75] opened 2023-10-11 20:49 UTC
### Describe Your Problem

I’ve had the plugin working before but I installed a fresh copy of homebridge and now it doesn’t work. Thank you

### Relevant log output

```shell
Devices 2: TypeError: Cannot convert undefined or null to object
```

### Device & Model

I have 12 locks. 1 Yale Conexis 11 Yale connected 

### Node.js Version

V18.17.1

### NPM Version

9

### Homebridge Version

V1.61

### Homebridge August Plugin Version

V1.21

### Homebridge Config UI X Plugin Version

4.60.6

### Operating System

Pi

**Comment by svengrun** [comment] 2023-10-26 03:16
Also getting this error. Did not do a re-install. Happy to do more debugging.

**Comment by simonrb2000** [comment] 2023-11-01 20:54
I have the same error :( 

I have 3x Yale Conexis locks

**Comment by donavanbecker** [comment] 2023-11-01 21:46
Can I get more logs?

**Comment by simonrb2000** [comment] 2023-11-01 21:50
This is all that is showing up in the live log. Where else would there be more logs? I have setup debug logs and only extra bits that show are my login details. No errors other than the one below:- 

[August] Discover Devices 2: TypeError: Cannot convert undefined or null to object

**Comment by rightedges** [comment] 2023-11-02 22:00
Same error as well. Please let us know how to generate more logs. Thanks.

**Comment by donavanbecker** [comment] 2023-11-02 22:04
Go to config ui > advance setting, change logs to debug

**Comment by simonrb2000** [comment] 2023-11-02 22:09
> Go to config ui > advance setting, change logs to debug

Sorry, can't see how to do that. Only have UI Settings and no debug option there. I set debug under the plugin itself and under Home Bridge settings, Environment Variables there is DEBUG however there is an empty text box next to it.

Update:- I may have broken homebridge. I typed Debug in the box and restarted it.. well it doesn't load now.. whoops
Update 2:- It is up and running however nothing new for the August plugin.. same stuff as before.. only contains api keys, passwords, usernames etc.. along with the error:-

```
[August] Discover Devices 2: TypeError: Cannot convert undefined or null to object
```

There's lots of debug stuff from other plugins now showing up.

**Comment by simonrb2000** [comment] 2023-11-02 22:24
This is all of it (passwords etc changed)

```
[02/11/2023, 22:13:39] [August] Initializing August platform...
[02/11/2023, 22:13:39] [August] [DEBUG] Using Config Logging: debug
[02/11/2023, 22:13:39] [August] [DEBUG] Finished initializing platform: August
[02/11/2023, 22:13:39] [August] Platform Config: {"logging":"debug"}
[02/11/2023, 22:13:39] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[02/11/2023, 22:13:39] [August] [DEBUG] Config OK
[02/11/2023, 22:13:39] Loading 1 accessories...
[02/11/2023, 22:13:39] [DS1019+] Initializing synology accessory...
[02/11/2023, 22:13:39] [DS1019+] Synology DS1019+ finished initializing!
[02/11/2023, 22:13:39] [August] [DEBUG] Executed didFinishLaunching callback
[02/11/2023, 22:13:39] [August] [DEBUG] augustId: si@hotmail.com, installId: 6xxxxxxec5-4ec7-8ebxxxxxx33552, password: xxxxxxcfi4, isValidated: true
[02/11/2023, 22:13:39] [August] [DEBUG] August Credentials: {"config":{"apiKey":"xxxxxxx-47721289d1d9","pnSubKey":"sub-c-10xxxxxxx619f8945a4f","installId":"6axxxxxxx8eb2-8b54272xxxxxx","idType":"email","augustId":"si@hotmail.com","password":"hxxxxxx4","countryCode":"US"}}
[02/11/2023, 22:13:40] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge D29C) is running on port 51873.
FetchError: Status 401 (undefined): undefined
[02/11/2023, 22:13:40] [August] Discover Devices 2: TypeError: Cannot convert undefined or null to object
```

**Comment by donavanbecker** [comment] 2023-11-02 22:46
> Same error as well. Please let us know how to generate more logs. Thanks.

<img width="597" alt="Screenshot 2023-11-02 at 5 45 31 PM" src="https://github.com/donavanbecker/homebridge-august/assets/9875439/66b1792c-42be-49c1-9f53-aeb77c6accc6">

**Comment by rightedges** [comment] 2023-11-02 23:00
Here is mine:

```
[11/2/2023, 3:46:08 PM] [August] [DEBUG] Using Config Logging: debug
[11/2/2023, 3:46:08 PM] [August] [DEBUG] Finished initializing platform: August
[11/2/2023, 3:46:08 PM] [August] Platform Config: {"logging":"debug"}
[11/2/2023, 3:46:08 PM] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[11/2/2023, 3:46:08 PM] [August] [DEBUG] Config OK
[11/2/2023, 3:46:08 PM] [August] [DEBUG] Executed didFinishLaunching callback
[11/2/2023, 3:46:08 PM] [August] [DEBUG] augustId: rightedges@gmail.com, installId: bXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX, password: XXXXXXXXX, isValidated: true
[11/2/2023, 3:46:08 PM] [August] [DEBUG] August Credentials: {"config":{"apiKey":"7XXXXXXXX-XXXX-XXXXX-XXXX-XXXXXXXXXXX","pnSubKey":"sub-c-1XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX","installId":"bXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","idType":"email","augustId":"rightedges@gmail.com","password":"XXXXXXXXX","countryCode":"US"}}
[11/2/2023, 3:46:08 PM] Homebridge v1.6.1 (HAP v0.11.1) (August) is running on port 43273.
[11/2/2023, 3:46:09 PM] [August] Discover Devices 2: TypeError: Cannot convert undefined or null to object
```

**Comment by donavanbecker** [comment] 2023-11-02 23:05
I also need both of your configs to make sure you have everything set up correctly. 
<img width="857" alt="Screenshot 2023-11-02 at 6 04 58 PM" src="https://github.com/donavanbecker/homebridge-august/assets/9875439/8dfdb285-6a6d-42e4-a483-121dc57530e3">
Click JSON Config and copy your Config. Please remove any sensitive info.

**Comment by rightedges** [comment] 2023-11-02 23:07
Here you go:

```json
{
    "name": "August",
    "credentials": {
        "augustId": "rightedges@gmail.com",
        "password": "XXXXXXXX",
        "contryCode": "US",
        "installId": "bXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "isValidated": true,
        "notice": "Keep your tokens a secret!"
    },
    "options": {
        "logging": "debug"
    },
    "_bridge": {
        "username": "0E:XX:XX:XX:XX:XX",
        "port": 43273
    },
    "platform": "August"
}
```

**Comment by stereoscott** [comment] 2023-11-18 02:23
I'm sure the "me too" comments aren't much help. Here is my log. Just added this plugin for the first time but couldn't see any devices. Checked the logs and saw this. 

```

successfully
[17/11/2023, 21:14:03] [August] [DEBUG] Using Config Logging: debug
[17/11/2023, 21:14:03] [August] [DEBUG] Finished initializing platform: August
[17/11/2023, 21:14:03] [August] Platform Config: {"logging":"debug"}
[17/11/2023, 21:14:03] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[17/11/2023, 21:14:03] [August] [DEBUG] Config OK
[17/11/2023, 21:14:03] [August] [DEBUG] Executed didFinishLaunching callback
[17/11/2023, 21:14:03] [August] [DEBUG] augustId: xxx, installId: xxx, password: xxx, isValidated: true
[17/11/2023, 21:14:03] [August] [DEBUG] August Credentials: {"installId":"xxx","augustId":"xxx","password":"xxx","countryCode":"US"}
[17/11/2023, 21:14:03] [August] [DEBUG] August Credentials: {"config":{"apiKey":"xxx","pnSubKey":"sub-c-xxx","installId":"xxx","idType":"email","augustId":"xxx","password":"xxx","countryCode":"US"}}
[17/11/2023, 21:14:04] Homebridge v1.6.1 (HAP v0.11.1) (August) is running on port 59244.
FetchError: Status 401 (undefined): undefined
[17/11/2023, 21:14:04] [August] Discover Devices 2: TypeError: Cannot convert undefined or null to object
```

EDIT: Sorry, I wasn't very clear. I just meant that I was going to add my own "me too" comment, and I wanted to touch on the fact that I realize it's not super helpful but was going to share my log for additional context :)

**Comment by adyrobady** [comment] 2023-11-18 10:12
I’m really sorry I know it doesn’t help anyone. I’m just so desperate to get the plug in working again. I just thought if there’s lots of people with the same problem it may get looked quicker. I’m very happy to make a donation if that helps
Thanks
Adrian
Sent from my iPhone

On 18 Nov 2023, at 02:23, Scott Meves ***@***.***> wrote:

﻿

I'm sure the "me too" comments aren't much help. Here is my log. Just added this plugin for the first time but could t see any devices. Checked the logs and saw this.


successfully
[17/11/2023, 21:14:03] [August] [DEBUG] Using Config Logging: debug
[17/11/2023, 21:14:03] [August] [DEBUG] Finished initializing platform: August
[17/11/2023, 21:14:03] [August] Platform Config: {"logging":"debug"}
[17/11/2023, 21:14:03] [August] [DEBUG] Using Default Refresh Rate (5 minutes).
[17/11/2023, 21:14:03] [August] [DEBUG] Config OK
[17/11/2023, 21:14:03] [August] [DEBUG] Executed didFinishLaunching callback
[17/11/2023, 21:14:03] [August] [DEBUG] augustId: xxx, installId: xxx, password: xxx, isValidated: true
[17/11/2023, 21:14:03] [August] [DEBUG] August Credentials: {"installId":"xxx","augustId":"xxx","password":"xxx","countryCode":"US"}
[17/11/2023, 21:14:03] [August] [DEBUG] August Credentials: {"config":{"apiKey":"xxx","pnSubKey":"sub-c-xxx","installId":"xxx","idType":"email","augustId":"xxx","password":"xxx","countryCode":"US"}}
[17/11/2023, 21:14:04] Homebridge v1.6.1 (HAP v0.11.1) (August) is running on port 59244.
FetchError: Status 401 (undefined): undefined
[17/11/2023, 21:14:04] [August] Discover Devices 2: TypeError: Cannot convert undefined or null to object

**Comment by Brodie01** [comment] 2023-11-22 17:29
Same issue, anything you need from me to assist in troubleshooting please let me know. I have an August 4th gen wifi lock. This is on a fresh install of home bridge, latest and greatest node and npm and fresh install of your plugin.

**Comment by donavanbecker** [comment] 2023-11-22 17:32
this is an API issue.

**Comment by Brodie01** [comment] 2023-11-22 17:40
> this is an API issue.

On August's side? So its broken for external apps trying to access?

**Comment by donavanbecker** [comment] 2023-11-22 17:59
[august-api](https://github.com/hufftheweevil/august-api)

**Comment by adyrobady** [comment] 2023-11-22 18:55
Ok. Thank you. I appreciate your time for looking into it for me

Thanks
Adrian
Sent from my iPhone

On 22 Nov 2023, at 17:59, Donavan Becker ***@***.***> wrote:

﻿

august-api<https://github.com/hufftheweevil/august-api>

**Comment by scottgreiner** [comment] 2023-12-15 18:26
So I'm still having this problem. "Discover Devices 2: TypeError: Cannot convert undefined or null to object" There have been 2 updates to this plug-in but the error continues. Was there a fix that I missed? Any advice?

**Comment by stereoscott** [comment] 2023-12-15 19:39
@scottgreiner keep your eyes peeled on https://github.com/hufftheweevil/august-api/issues/6, as that library provides the interface to the August API for this plugin. You can hit the button to get notified if there is any activity on the issue.

**Comment by chrisjameschamp** [comment] 2024-01-16 06:38
The issue is still occurring for myself and not resolved

**Comment by Marpanet** [comment] 2024-01-29 14:28
The first time I install, it was working but after I had to restart Homebridge for another Plugins it started with the message, I dont know if it is a problem from August side after trying to reconnect.

**Comment by donavanbecker** [comment] 2024-01-30 15:39
sorry everyone. I am working on redoing the august-api module. If I am successful then I will be able to use it with this plugin.

**Comment by donavanbecker** [comment] 2024-01-31 04:22
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-august@beta/>=1.3.5-beta.4/orange)](https://www.npmjs.com/package/homebridge-august)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-august/wiki/Beta-Version)

**Comment by donavanbecker** [comment] 2024-01-31 05:27
Release v2.0.0, which is a major change. I am going to close this, if you are still having issues please open a new issue with logs. Thanks!

**Closed as completed by donavanbecker** 2024-01-31 05:27 UTC
Labels: bug, pinned
